# main server properties
server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: spring-boot-demo-redis
# redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    timeout: 5000ms
#  redis集群
#    cluster:
#      nodes:
#        - 127.0.0.1:6379
#        - 127.0.0.1:6380
#        - 127.0.0.1:6381
#  redis连接池 默认连接池
    lettuce:
      pool:
        max-active: 100  #连接池最大连接数（使用负值表示没有限制）
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 5 # 连接池中的最小空闲连接
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
#    sentinel:
#      master: master6019
#      nodes: 127.0.0.1:16019,127.0.0.1:16019,127.0.0.1:16019
